# -*- coding: utf-8 -*-
"""LAB-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOV4fBnwh710cFBEKvjfODBhycInY5K6
"""

import cv2
from google.colab.patches import cv2_imshow

# Read image
image = cv2.imread("images (2).jpg")

if image is None:
    print("Error: Image not found.")
else:
    print("Original Image")
    cv2_imshow(image)

    # Apply Gaussian Blur
    blur = cv2.GaussianBlur(image, (5, 5), 10)

    print("Blurred Image")
    cv2_imshow(blur)

    # Save blurred image
    cv2.imwrite("blurred_image.jpg", blur)
