# -*- coding: utf-8 -*-
"""LAB-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_UKPaZkfuhvXHc-knDmg_iophME7_mA
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

# Read image in grayscale
img = cv2.imread("images (4).jpg", cv2.IMREAD_GRAYSCALE)

# Create kernel
kernel = np.ones((5,5), np.uint8)

# Dilate image
dilated = cv2.dilate(img, kernel, iterations=1)

# Display images
print("Original Image")
cv2_imshow(img)

print("Dilated Image")
cv2_imshow(dilated)

# Save output
cv2.imwrite("Dilated_Image.jpg", dilated)
